#!/usr/bin/env python 

import sys

def main():
    if (len(sys.argv) != 2):
        print("Error: You must specify if the process is a client or a server..")
        sys.exit(1)

    if (sys.argv[1] == "server"):
        from source.server.server import Server
        server = Server()
        server.run()
    elif (sys.argv[1] == "client"):
        from source.client.client import Client
        client = Client()
        client.run()
    else:
        print("Error: You must specify if the process is a client or a server..")
        sys.exit(1)
    exit(0)

if __name__ == "__main__":
    main()